name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs when you push to main branch
  pull_request:
    branches:
      - main   # Runs on pull requests to main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Rental-Room-Booking-System
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot Rental-Room-Booking-System
        run: mvn clean install -DskipTests

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build